/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Contacts: typeof import('./src/components/contacts.vue')['default']
    Equipment_cards: typeof import('./src/components/equipment/equipment_cards.vue')['default']
    Gallery: typeof import('./src/components/gallery/gallery.vue')['default']
    Gallery_card: typeof import('./src/components/gallery/gallery_card.vue')['default']
    Header: typeof import('./src/components/header/header.vue')['default']
    Hero_section: typeof import('./src/components/header/hero_section.vue')['default']
    Mobile_header: typeof import('./src/components/header/mobile_header.vue')['default']
    Order_dialog: typeof import('./src/components/order_dialog.vue')['default']
    Partners: typeof import('./src/components/partners.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Services_gallery: typeof import('./src/components/equipment/services_gallery.vue')['default']
    Table_card: typeof import('./src/components/equipment/table_card.vue')['default']
  }
}
