/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cards: typeof import('./src/components/cards.vue')['default']
    Gallery: typeof import('./src/components/gallery.vue')['default']
    Gallery_card: typeof import('./src/components/gallery_card.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Hero_section: typeof import('./src/components/hero_section.vue')['default']
    Partners: typeof import('./src/components/partners.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table_card: typeof import('./src/components/table_card.vue')['default']
  }
}
